-- =====================================================================================
-- V2 — posts 조회 인덱스 **후보 A**: (author_id, id DESC)
--
-- 근거: 마스터 §4.1 후보 규정 / 로드맵 20-phase-1-baseline.md P1-13 / M0 분석 docs/perf/m0.md
--
-- 왜 지금 넣는가
--   V1이 posts 조회용 보조 인덱스를 일부러 비워 둔 것은 M0("인덱스 없음")를 성립시키기 위해서였다.
--   M0 측정이 끝났으므로 이제 인덱스를 도입한다. 순서가 반대였다면
--   "인덱스만으로 얼마나 개선되는가"(§9.2 M1)에 답할 대조군이 사라진다.
--
-- M0가 지목한 것 (docs/perf/m0.md "원인 분석")
--   · EXPLAIN        : ORDER BY p.id DESC 를 받아 줄 인덱스가 없어 `Using temporary; Using filesort`
--   · EXPLAIN ANALYZE: heavy 코호트 기준 정렬 입력 14,963행 / 409ms.
--                      normal 3,061행/65.5ms · light 322행/6.1ms 로 시간이 정렬 입력 행수에 비례한다
--                      — 비용의 주체는 JOIN 이 아니라 정렬이다
--   · slow log       : Rows_examined p50 15,606 (반환 25건 대비 약 600배)
--   · buffer pool    : 히트율 ≥ 99.9% — 데이터는 메모리에 다 있다. 병목은 I/O 가 아니라 CPU/정렬이다
--
-- 이 인덱스가 노리는 것
--   author 별로 id 역순 접근을 인덱스가 직접 제공하게 만들어 filesort 를 없앤다.
--   JOIN 은 followee(author) 하나하나에 대해 "그 author 의 최신 글"을 찾는 형태이므로,
--   선행 컬럼 author_id 로 진입한 뒤 id 가 이미 내림차순으로 정렬돼 있으면
--   정렬 단계 자체가 사라지고 LIMIT 25 를 조기 종료로 처리할 여지가 생긴다.
--
-- DESC 를 명시하는 이유
--   MySQL 8.0 은 진짜 내림차순 인덱스를 지원한다(5.7 까지는 파싱만 하고 무시했다).
--   ORDER BY 방향과 인덱스 방향을 문자 그대로 일치시켜, 역방향 스캔에 기대지 않게 한다.
--
-- fk_posts_author 와의 관계 (실측으로 확인된 동작)
--   V1 의 FK 제약 때문에 InnoDB 가 만든 author_id 단일 컬럼 인덱스 `fk_posts_author` 가 있었다
--   (M0 의 EXPLAIN 이 p 를 fk_posts_author ref 로 읽은 것이 그 존재 증거).
--   이 마이그레이션이 같은 선행 컬럼(author_id)의 인덱스를 만들면 InnoDB 는
--   **자동 생성 인덱스 fk_posts_author 를 조용히 제거하고 FK 를 이 인덱스에 재바인딩한다** —
--   적용 후 SHOW INDEX 에 fk_posts_author 가 없는 것이 실측 결과다.
--   따라서 이 인덱스를 이후에 지우려면 FK 가 옮겨 탈 다른 author_id 선행 인덱스가
--   먼저 존재해야 한다(V3 의 적용 순서가 그 제약에서 나왔다 — ERROR 1553 실측).
--
-- 적용 범위
--   이 마이그레이션은 후보 A 를 재는 데 쓴다. 후보 B 는 V3 이고,
--   둘 중 무엇을 채택할지는 P1-13 의 실측 비교(EXPLAIN ANALYZE + heavy 단축 부하)가 정한다.
--   V2 → V3 라는 이력 자체가 그 비교의 기록이다(마스터 §3 — Flyway 를 넣은 이유).
-- =====================================================================================

CREATE INDEX idx_posts_author_id_desc ON posts (author_id, id DESC);
